-- Inserindo usuários na tabela tb_users (O userId é gerado automaticamente)
INSERT INTO tb_users (name, password) VALUES ('Nicolas Kogus', 'java_dev_2026');
INSERT INTO tb_users (name, password) VALUES ('Kiara Assassina', 'miau_bravo_123');
INSERT INTO tb_users (name, password) VALUES ('Muffin Sapeca', 'quero_petisco');
INSERT INTO tb_users (name, password) VALUES ('Meliodas', 'full_counter');
INSERT INTO tb_users (name, password) VALUES ('Ban', 'fox_sin');
INSERT INTO tb_users (name, password) VALUES ('King', 'chastiefol');
INSERT INTO tb_users (name, password) VALUES ('Diane', 'gideon_warrior');
INSERT INTO tb_users (name, password) VALUES ('Gowther', 'invasion_light');
INSERT INTO tb_users (name, password) VALUES ('Merlin', 'infinity_spell');
INSERT INTO tb_users (name, password) VALUES ('Escanor', 'praise_the_sun');
INSERT INTO tb_users (name, password) VALUES ('Elizabeth Liones', 'ark_blessing');
INSERT INTO tb_users (name, password) VALUES ('Arthur Pendragon', 'excalibur_king');
INSERT INTO tb_users (name, password) VALUES ('Zeldris', 'piety_commandment');
INSERT INTO tb_users (name, password) VALUES ('Estarossa', 'benevolence_sun');
INSERT INTO tb_users (name, password) VALUES ('Gilthunder', 'thunder_bolt');
INSERT INTO tb_users (name, password) VALUES ('Margaret Liones', 'princess_love');
INSERT INTO tb_users (name, password) VALUES ('Howzer', 'rising_tornado');
INSERT INTO tb_users (name, password) VALUES ('Guila', 'explosion_rapier');
INSERT INTO tb_users (name, password) VALUES ('Jericho', 'god_speed_ice');
INSERT INTO tb_users (name, password) VALUES ('Hendrickson', 'acid_power');
INSERT INTO tb_users (name, password) VALUES ('Dreyfus', 'break_strength');
INSERT INTO tb_users (name, password) VALUES ('Bartra Liones', 'vision_king');
INSERT INTO tb_users (name, password) VALUES ('Hawk', 'sir_pork');
INSERT INTO tb_users (name, password) VALUES ('Cath Palug', 'chaos_beast');
INSERT INTO tb_users (name, password) VALUES ('Gelda', 'vampire_love');
INSERT INTO tb_users (name, password) VALUES ('Zhivago', 'werefox_father');
INSERT INTO tb_users (name, password) VALUES ('Elaine', 'guardian_saint');
INSERT INTO tb_users (name, password) VALUES ('Matrona', 'giant_fang');
INSERT INTO tb_users (name, password) VALUES ('Gerheade', 'fairy_servant');
INSERT INTO tb_users (name, password) VALUES ('Wild', 'boar_brother');

-- Inserindo livros na tabela tb_books (Sem vínculo de usuário)
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Clean Code', 'Robert C. Martin', '2008-08-01');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Java: The Complete Reference', 'Herbert Schildt', '2018-12-12');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Spring Boot in Action', 'Craig Walls', '2016-01-03');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Manual da Caça Perfeita', 'Kiara Cat', '2024-05-20');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Como Roubar Petiscos', 'Muffin Dog', '2025-10-15');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('The Seven Deadly Sins: Vol 1', 'Nakaba Suzuki', '2012-10-10');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('The Seven Deadly Sins: Vol 2', 'Nakaba Suzuki', '2013-01-15');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Guia de Culinária de Liones', 'Ban', '2014-06-20');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Botânica da Floresta das Fadas', 'King', '2015-03-12');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Geologia das Terras Gigantes', 'Diane', '2016-08-25');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Poesia e Coração', 'Gowther', '2017-11-30');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Física Quântica e Magia', 'Merlin', '2018-02-14');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('O Sol e o Poder Absoluto', 'Escanor', '2019-07-07');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('O Senhor dos Anéis', 'J.R.R. Tolkien', '1954-07-29');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Dom Casmurro', 'Machado de Assis', '1899-01-01');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('O Alquimista', 'Paulo Coelho', '1988-05-15');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('1984', 'George Orwell', '1949-06-08');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Revolução dos Bichos', 'George Orwell', '1945-08-17');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Harry Potter e a Pedra Filosofal', 'J.K. Rowling', '1997-06-26');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('O Pequeno Príncipe', 'Antoine de Saint-Exupéry', '1943-04-06');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('O Código Da Vinci', 'Dan Brown', '2003-03-18');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Crônicas de Nárnia', 'C.S. Lewis', '1950-10-16');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('O Hobbit', 'J.R.R. Tolkien', '1937-09-21');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('A Menina que Roubava Livros', 'Markus Zusak', '2005-09-01');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Cem Anos de Solidão', 'Gabriel García Márquez', '1967-05-30');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('O Caçador de Pipas', 'Khaled Hosseini', '2003-05-22');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Orgulho e Preconceito', 'Jane Austen', '1813-01-28');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Ensaio Sobre a Cegueira', 'José Saramago', '1995-10-01');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('O Nome da Rosa', 'Umberto Eco', '1980-01-01');
INSERT INTO tb_books (name, author, year_of_publication) VALUES ('Drácula', 'Bram Stoker', '1897-05-26');